---
apiVersion: v1
kind: Service
metadata:
  name: routing
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  dc_1_mapping
      prefix: /test/
      headers:
        x-dc: Odd
      service: https://qotm:443
      tls: ambassador-consul
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  dc_2_mapping
      prefix: /test/
      headers:
        x-dc: Even
      service: https://microdonut:443
      tls: ambassador-consul
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  dc_fallback_mapping
      prefix: /test/
      service: ambassador
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  httpbin_mapping
      prefix: /httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org   
spec:
  ports:
  - name: httpbin
    port: 80
