apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: qotm-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: qotm
spec:
  hosts:
  - "*"
  gateways:
  - qotm-gateway
  http:
  - match:
    - uri:
        exact: /quote/0
    route:
    - destination:
        host: qotm
        port:
          number: 443
